{% set version = "0.2.0" %}

package:
  name: ciso
  version: {{ version }}

source:
  url: https://github.com/ioos/ciso/archive/v{{ version }}.tar.gz
  sha256: 7a4859b4344d6a29cf075d37e4b0e62e997286d1355c5e8705109c04e0a13afb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ciso
  commands:

about:
  home: https://github.com/ioos/ciso
  license: MIT
  license_file: LICENSE.txt
  summary: Cythonized Iso Surfaces (CISO)

extra:
  recipe-maintainers:
    - ocefpaf
