{% set version = "0.0.1" %}

package:
  name: ciso
  version: {{ version }}

source:
  url: https://github.com/ioos/ciso/archive/v{{ version }}.tar.gz
  sha256: 8d28c4df6eca3b683d8a2efed8da9b0699c98efe3c53e23203a1c1169f9d54b3

build:
  number: 1003
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ciso
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/ioos/ciso
  license: MIT
  license_file: LICENSE.txt
  summary: 'Cythonized Iso Surfaces (CISO)'

extra:
  recipe-maintainers:
    - ocefpaf
