{% set version = "0.1.0" %}

package:
  name: ciso
  version: {{ version }}

source:
  url: https://github.com/ioos/ciso/archive/v{{ version }}.tar.gz
  sha256: d2a2a7d76fd23e7b20a715bd02e34e2843c3924c75ea4253dc141bc8628e2af0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ciso
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/ioos/ciso
  license: MIT
  license_file: LICENSE.txt
  summary: 'Cythonized Iso Surfaces (CISO)'

extra:
  recipe-maintainers:
    - ocefpaf
