{% set version = "0.0.1" %}

package:
  name: ciso
  version: {{ version }}

source:
  url: https://github.com/ioos/ciso/archive/v{{ version }}.tar.gz
  sha256: 8d28c4df6eca3b683d8a2efed8da9b0699c98efe3c53e23203a1c1169f9d54b3

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy        # [py27]
    - numpy        # [py35]
    - numpy         # [py36]
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [py27]
    - {{ pin_compatible('numpy') }}   # [py35]
    - {{ pin_compatible('numpy') }}   # [py36]

test:
  imports:
    - ciso
  commands:
    - conda inspect linkages -p $PREFIX ciso  # [not win]
    - conda inspect objects -p $PREFIX ciso  # [osx]

about:
  home: https://github.com/ioos/ciso
  license: MIT
  license_file: LICENSE.txt
  summary: 'Cythonized Iso Surfaces (CISO).'

extra:
  recipe-maintainers:
    - ocefpaf
