{% set name = "ciso" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ciso-{{ version }}.tar.gz
  sha256: f91a5a43d116703d7038be34f694d290a5bb0d0c9a63ec7db8d1653e6e8588da

build:
  skip: true  # [py<38 or python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - setuptools-scm
    - pip
  run:
    - python
    - cython
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ciso
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ioos/ciso
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: Cythonized Iso Surfaces (CISO)

extra:
  recipe-maintainers:
    - ocefpaf
