travis:
  secure:
    BINSTAR_TOKEN: h/quog6kc6Q6xxXz0zyFCHsUVEVS6er9XgFAv6tm+2WaP0Cupw7TmMkGE2NSA5ckXrALhXF0Dm7p2YP/hTbrv13/GO808w/HOhFuIZ2v4GpLTdOFCzj85vLy5xc80OEpkYNxFRAFQJU5vP4BavVEC6B2YRE0YvxcxJfy9e23AEVgXkLH3KEuiGpRgGHJJOuRl4Oje+unXXNalH8eCkvM1Or7VaXytbXrba2jWx5/3z2cgfGe1zguWc7lkyprg1mK6IrcpmV8z1NHY1ncq7bB63+oAwPBIiTz3qvGnFAipqgB4UU6+1ONj94OhSwmfCJBg3jt/k6bFNkVh3DeLn94XzHZPLJ1Rs/Qom/zGGpRVzY355IIqMelMQN80JashcVbiyRsDairGBaw3F/2AkCw0p2DSUAQ7BOCWlkSKGugE/OwQPEaZrhv4e2VAhzBxqrpAd7WOqtkLCBHIs6OxgHOdCpx3wKxUFpCaN2dY/9wY33jqo3bWs4zs80/7bsqiFT/wmFvAloeKu5rxOo4fs03FWMqCVDaJWH6JhSB47e+lmendeWKXp+YVViZk6dnS7F6rSXiuZg7IoVR69euk/LxtCe4tiDnoa7Ajp7upgodODJAym6RrweliZQcpnl7Mtq3Kl09/PYvOYgUHQu7ehco5lzv1qgf4pEXWajzcTpjvX4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
