appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ItTvOxpbZsJ6V4ntjqqH+HOJgWlMze/PwuPrbf8qcvzALsplStJWqKovA2ASrUu5VV9t347gl59eKj15UbWHzEsI9TH07EtWkVwj8YQo12G7ANCCI0aFQky869deMgtKzsXYAzd00r/5g96lqrBbMXLwfqIN37Op7JqJRueTTmQcxybeBEoJ9Gbl0QB5YA2RAYan/yzkP2xLjLqTT4f/e/Jrnxb89BZwlVBOcPuQDrvfp4sF18g/UIBBcnBmX3ti1gj4CJ6oAyvpChR+or/HryvLEJOFsQ2Hx7EQalITEhgSemljWVh8AdXsohDDoCEDH8lg8rvscVWXgmt5J2AVT0E9GXhpJ0bYVWhIF2A1Kv4B/bEx9B3lSyUrdLQ4w/fdYm5s4qlXDAjEVnWr9uUR5G71865Y+VyuEgBTHQJxJK8kucRHGMH045ZbG6PincT0VUwo5EUhEcvGdafszkr1HV1zMMQlQ2kaCwTgtNdqfyr2MdjRbXa2Gcoq0u9o0Twc31njQnuasD5Ld35ZoIgX5BZNEzDguv6aQK4LIrY1LyS+6sydehcLDvU3Z5FR14M0lviTGor4cLjoiu91BQXtbWupFgSUtX9Tz047ssnoNeduR1/Ia65dGbnKKkjS+fCAKhn33/91cZ60aQBX8AiC2WMrbI11glwbsfNrTUswIkk=}
provider:
  win: azure
